//! Production plist fixtures closure for the 0.10.0 release gate.

use consema_core::PortableValue;
use consema_document::{
    FormationStatus, MaterializationRequest, MaterializationResult, MaterializationStyleId,
    NewlinePolicy, ProfileId, SourceEncoding,
};
use consema_plist::{
    Document, PlistDict, PlistDocument, PlistEncodingSelection, PlistParseLimits, PlistProfile,
    PlistValue, PlistValueRef, ProjectionRequest, ProjectionResult, UidPolicy, materialize, parse,
};
use std::sync::Arc;

const XML_FIXTURES: &[(&str, &[u8])] = &[
    (
        "com.example.preferences.plist",
        include_bytes!("../../../conformance/fixtures/plist/xml/com.example.preferences.plist"),
    ),
    (
        "com.example.repeated-keys.plist",
        include_bytes!("../../../conformance/fixtures/plist/xml/com.example.repeated-keys.plist"),
    ),
    (
        "Info.plist",
        include_bytes!("../../../conformance/fixtures/plist/xml/Info.plist"),
    ),
    (
        "com.example.archiver-sample.plist",
        include_bytes!("../../../conformance/fixtures/plist/xml/com.example.archiver-sample.plist"),
    ),
];

const BINARY_FIXTURES: &[(&str, &[u8])] = &[
    (
        "com.example.preferences.binary.plist",
        include_bytes!(
            "../../../conformance/fixtures/plist/binary/com.example.preferences.binary.plist"
        ),
    ),
    (
        "com.example.archiver-sample.binary.plist",
        include_bytes!(
            "../../../conformance/fixtures/plist/binary/com.example.archiver-sample.binary.plist"
        ),
    ),
    (
        "com.example.shared-refs.binary.plist",
        include_bytes!(
            "../../../conformance/fixtures/plist/binary/com.example.shared-refs.binary.plist"
        ),
    ),
];

fn fixture_source<'a>(fixtures: &'a [(&'a str, &'a [u8])], name: &str) -> &'a [u8] {
    fixtures
        .iter()
        .find(|(fixture_name, _)| *fixture_name == name)
        .map(|(_, source)| *source)
        .expect("known fixture")
}

fn parse_xml_fixture(source: &[u8]) -> Document {
    let bytes: Arc<[u8]> = Arc::from(source);
    let document = parse(
        bytes,
        PlistProfile::XmlV1,
        PlistEncodingSelection::ProfileDefault,
        PlistParseLimits::default(),
    )
    .expect("fixture forms");
    assert_eq!(
        document.status(),
        FormationStatus::Complete,
        "fixture must be complete: {:?}",
        document.diagnostics()
    );
    document
}

fn parse_binary_fixture(source: &[u8]) -> Document {
    let bytes: Arc<[u8]> = Arc::from(source);
    let document = parse(
        bytes,
        PlistProfile::BinaryV1,
        PlistEncodingSelection::ProfileDefault,
        PlistParseLimits::default(),
    )
    .expect("fixture forms");
    assert_eq!(
        document.status(),
        FormationStatus::Complete,
        "fixture must be complete: {:?}",
        document.diagnostics()
    );
    document
}

fn xml_request() -> MaterializationRequest {
    MaterializationRequest::new(
        ProfileId::new("plist.xml", 1),
        MaterializationStyleId::new("plist.xml-canonical", 1),
    )
}

fn binary_request() -> MaterializationRequest {
    MaterializationRequest::new(
        ProfileId::new("plist.binary", 1),
        MaterializationStyleId::new("plist.binary-canonical", 1),
    )
    .with_encoding(SourceEncoding::Binary)
    .with_newline(NewlinePolicy::None)
}

/// The archiver fixture carries UID values, so its projection must include
/// them; every other fixture projects under the default exclude policy.
fn fixture_uid_policy(name: &str) -> UidPolicy {
    if name == "com.example.archiver-sample.binary.plist" {
        UidPolicy::Include
    } else {
        UidPolicy::Exclude
    }
}

/// Exhaustive binary structural coverage: the regions span every raw byte.
fn assert_binary_coverage(document: &Document, source: &[u8], name: &str) {
    let index = document.binary_structural_index().expect("index");
    let covered: usize = index
        .regions()
        .iter()
        .map(|region| region.span().len())
        .sum();
    assert_eq!(covered, source.len(), "{name} binary region coverage");
}

/// One full closure leg: project exactly, materialize canonically, reparse
/// the exact generated bytes, and require native-model equality and a
/// projection fixed point (RFC 0013 §9, §10.3).
fn assert_loop_closure(
    document: &Document,
    name: &str,
    request: MaterializationRequest,
    uid_policy: UidPolicy,
) {
    let consema_plist::ProjectionResult::Complete(first) =
        consema_plist::project(document, ProjectionRequest::value_tree_with_uid(uid_policy))
    else {
        panic!("{name} must project exactly");
    };
    let complete = match materialize(&first.value, &request) {
        MaterializationResult::Complete(complete) => complete,
        MaterializationResult::Failed(attempt) => {
            panic!("{name} must materialize canonically: {:?}", attempt.failure);
        }
    };
    assert_eq!(
        complete.document.status(),
        FormationStatus::Complete,
        "{name} materialized document is complete"
    );
    assert_eq!(
        complete.document.document(),
        document.document(),
        "{name} materialization reparses to the same native model"
    );
    let consema_plist::ProjectionResult::Complete(second) = consema_plist::project(
        &complete.document,
        ProjectionRequest::value_tree_with_uid(uid_policy),
    ) else {
        panic!("{name} reparsed document must project exactly");
    };
    assert_eq!(
        second.value, first.value,
        "{name} projection must be a materialization fixed point"
    );
}

/// Sorted UID values of one native document's arena (RFC 0013 §6).
fn native_uid_values(native: &PlistDocument) -> Vec<u32> {
    let mut values = (0..native.node_count())
        .filter_map(|index| match native.get(PlistValueRef::from_index(index)) {
            Some(PlistValue::Uid(uid)) => Some(uid.value()),
            _ => None,
        })
        .collect::<Vec<_>>();
    values.sort_unstable();
    values
}

/// Value of the first dictionary entry with the exact key, or `None`.
fn entry_value<'a>(
    native: &'a PlistDocument,
    dict: &PlistDict,
    key: &str,
) -> Option<&'a PlistValue> {
    dict.entries()
        .iter()
        .find(|entry| entry.key().to_unicode().as_deref() == Ok(key))
        .map(|entry| native.get(entry.value()).expect("resolvable"))
}

/// Collects every typed UID member of a `plist.value-tree@1` record: an
/// Object of exactly one `uid` member holding an integer (RFC 0013 §9).
fn collect_record_uids(value: &PortableValue, out: &mut Vec<u32>) {
    if let Some(object) = value.as_object() {
        if object.len() == 1 && object[0].key() == "uid" {
            if let Some(integer) = object[0].value().as_integer() {
                let integer = integer.to_i64().expect("uid integer");
                out.push(u32::try_from(integer).expect("uid in range"));
                return;
            }
        }
        for entry in object {
            collect_record_uids(entry.value(), out);
        }
        return;
    }
    if let Some(entries) = value.as_entry_mapping() {
        for entry in entries {
            collect_record_uids(entry.value(), out);
        }
        return;
    }
    if let Some(elements) = value.as_sequence() {
        for element in elements {
            collect_record_uids(element, out);
        }
    }
}

#[test]
fn plist_fixtures_form_completely_and_round_trip_byte_exactly() {
    for (name, source) in XML_FIXTURES {
        let document = parse_xml_fixture(source);
        assert_eq!(
            document.render(),
            *source,
            "{name} render must be byte-exact"
        );
        assert!(
            document.diagnostics().is_empty(),
            "{name} must form without diagnostics"
        );
        let index = document.lossless_structural_index().expect("index");
        let covered: usize = index.pieces().iter().map(|piece| piece.span().len()).sum();
        assert_eq!(covered, source.len(), "{name} lossless coverage");
        assert_eq!(
            document.lossless_syntax_kinds().expect("kinds").len(),
            index.pieces().len(),
            "{name} kinds parallel pieces"
        );
    }
    for (name, source) in BINARY_FIXTURES {
        let document = parse_binary_fixture(source);
        assert_eq!(
            document.render(),
            *source,
            "{name} render must be byte-exact"
        );
        assert!(
            document.diagnostics().is_empty(),
            "{name} must form without diagnostics"
        );
        assert_binary_coverage(&document, source, name);
    }
}

#[test]
fn plist_fixtures_project_exactly_and_materialize_back_to_the_same_record() {
    for (name, source) in XML_FIXTURES {
        let document = parse_xml_fixture(source);
        assert_loop_closure(&document, name, xml_request(), UidPolicy::Exclude);
    }
    for (name, source) in BINARY_FIXTURES {
        let document = parse_binary_fixture(source);
        assert_loop_closure(&document, name, binary_request(), fixture_uid_policy(name));
    }
}

#[test]
fn plist_fixtures_convert_between_representations_with_native_equality() {
    // XML -> binary -> XML over the XML preference fixture (the M4 round-trip
    // gate over a production shape).
    let source = fixture_source(XML_FIXTURES, "com.example.preferences.plist");
    let xml = parse_xml_fixture(source);
    let converted = xml
        .convert_to(PlistProfile::BinaryV1, PlistParseLimits::default())
        .expect("xml preference fixture converts to binary");
    assert!(
        converted.report().representation_changed(),
        "conversion publishes the representation change"
    );
    assert_eq!(
        converted.document().document(),
        xml.document(),
        "converted binary native model equals the xml source"
    );
    let back = converted
        .document()
        .convert_to(PlistProfile::XmlV1, PlistParseLimits::default())
        .expect("converted binary converts back to xml");
    assert_eq!(
        back.document().document(),
        xml.document(),
        "xml -> binary -> xml keeps the native model"
    );

    // binary -> XML -> binary over the binary preference fixture; every fact
    // of that fixture is XML-expressible by design.
    let source = fixture_source(BINARY_FIXTURES, "com.example.preferences.binary.plist");
    let binary = parse_binary_fixture(source);
    let converted = binary
        .convert_to(PlistProfile::XmlV1, PlistParseLimits::default())
        .expect("binary preference fixture converts to xml");
    assert!(
        converted.report().representation_changed(),
        "conversion publishes the representation change"
    );
    assert_eq!(
        converted.document().document(),
        binary.document(),
        "converted xml native model equals the binary source"
    );
    let back = converted
        .document()
        .convert_to(PlistProfile::BinaryV1, PlistParseLimits::default())
        .expect("converted xml converts back to binary");
    assert_eq!(
        back.document().document(),
        binary.document(),
        "binary -> xml -> binary keeps the native model"
    );
}

#[test]
fn plist_archiver_fixture_preserves_uids_without_rebuilding_tables() {
    let source = fixture_source(BINARY_FIXTURES, "com.example.archiver-sample.binary.plist");
    let document = parse_binary_fixture(source);
    let native = document.document().expect("native document");

    // UID values are typed native values: the payload's `$class` reference
    // and the `$top` root reference (R-6).
    assert_eq!(native_uid_values(native), vec![4, 5]);

    // $objects holds the objects themselves, index 0 is "$null", and the
    // payload and its class descriptor follow.
    let root = native.root_value().as_dict().expect("root dict");
    let objects = entry_value(native, root, "$objects")
        .expect("$objects member")
        .as_array()
        .expect("$objects array");
    assert_eq!(objects.elements().len(), 3, "$objects has three members");
    let objects = objects
        .elements()
        .iter()
        .map(|reference| native.get(*reference).expect("resolvable"))
        .collect::<Vec<_>>();
    assert_eq!(
        objects[0]
            .as_string()
            .expect("$null string")
            .to_unicode()
            .as_deref(),
        Ok("$null"),
        "objects[0] is the $null string"
    );
    let payload = objects[1].as_dict().expect("payload dict");
    assert_eq!(
        entry_value(native, payload, "$class")
            .expect("$class member")
            .as_uid()
            .expect("uid")
            .value(),
        4,
        "the payload's $class member is the UID reference to the class descriptor"
    );
    assert_eq!(
        entry_value(native, payload, "title")
            .expect("title member")
            .as_string()
            .expect("string")
            .to_unicode()
            .as_deref(),
        Ok("sample")
    );
    let top = entry_value(native, root, "$top")
        .expect("$top member")
        .as_dict()
        .expect("$top dict");
    assert_eq!(
        entry_value(native, top, "root")
            .expect("root member")
            .as_uid()
            .expect("uid")
            .value(),
        5,
        "the $top root member is the UID reference into $objects"
    );

    // Projection with the Include policy publishes typed UID members, never
    // integers.
    let ProjectionResult::Complete(projection) = consema_plist::project(
        &document,
        ProjectionRequest::value_tree_with_uid(UidPolicy::Include),
    ) else {
        panic!("archiver fixture must project with UIDs included");
    };
    let mut record_uids = Vec::new();
    collect_record_uids(&projection.value, &mut record_uids);
    record_uids.sort_unstable();
    assert_eq!(record_uids, vec![4, 5]);

    // The canonical binary materialization reparses to the same native model:
    // UIDs survive as values and the $objects/$class tables are never rebuilt.
    let complete = match materialize(&projection.value, &binary_request()) {
        MaterializationResult::Complete(complete) => complete,
        MaterializationResult::Failed(attempt) => {
            panic!(
                "the projected archiver record must materialize: {:?}",
                attempt.failure
            );
        }
    };
    assert_eq!(
        complete.document.document(),
        document.document(),
        "archiver UIDs survive the canonical binary materialization reparse"
    );
    let reparsed = complete.document.document().expect("native document");
    assert_eq!(native_uid_values(reparsed), vec![4, 5]);
    let reparsed_root = reparsed.root_value().as_dict().expect("root dict");
    assert_eq!(
        entry_value(reparsed, reparsed_root, "$archiver")
            .expect("$archiver member")
            .as_string()
            .expect("string")
            .to_unicode()
            .as_deref(),
        Ok("NSKeyedArchiver"),
        "the archive table strings survive verbatim"
    );
    assert_eq!(
        entry_value(reparsed, reparsed_root, "$version")
            .expect("$version member")
            .as_integer()
            .expect("integer")
            .value(),
        100_000
    );
}

#[test]
fn plist_utf16_xml_fixture_round_trips() {
    // Following the encoding-corpus 体例 (tests/xml_encoding_corpus.rs), the
    // UTF-16 source is generated in memory rather than stored as a fixture
    // file; the BOM alone selects the encoding under the profile default.
    let text = "<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n    <dict>\n        <key>language</key>\n        <string>en-US</string>\n        <key>greeting</key>\n        <string>你好, 世界!</string>\n        <key>retry-count</key>\n        <integer>-3</integer>\n        <key>enabled</key>\n        <true/>\n    </dict>\n</plist>\n";
    let mut bytes = vec![0xFF, 0xFE];
    for unit in text.encode_utf16() {
        bytes.extend_from_slice(&unit.to_le_bytes());
    }
    let document = parse(
        Arc::from(bytes.as_slice()),
        PlistProfile::XmlV1,
        PlistEncodingSelection::ProfileDefault,
        PlistParseLimits::default(),
    )
    .expect("utf-16 fixture forms");
    assert_eq!(
        document.status(),
        FormationStatus::Complete,
        "a UTF-16LE BOM fixture forms completely"
    );
    assert_eq!(
        document.render(),
        bytes.as_slice(),
        "utf-16 render must be byte-exact"
    );
    assert!(
        document.diagnostics().is_empty(),
        "utf-16 fixture must form without diagnostics"
    );
    let index = document.lossless_structural_index().expect("index");
    let covered: usize = index.pieces().iter().map(|piece| piece.span().len()).sum();
    assert_eq!(covered, bytes.len(), "utf-16 lossless coverage");

    // The full closure over the decoded document: project, canonical XML
    // materialization, reparse, native-model equality, projection fixed point.
    let ProjectionResult::Complete(first) =
        consema_plist::project(&document, ProjectionRequest::value_tree())
    else {
        panic!("utf-16 fixture must project exactly");
    };
    let MaterializationResult::Complete(complete) = materialize(&first.value, &xml_request())
    else {
        panic!("utf-16 fixture must materialize canonically");
    };
    assert_eq!(
        complete.document.document(),
        document.document(),
        "utf-16 materialization reparses to the same native model"
    );
    let ProjectionResult::Complete(second) =
        consema_plist::project(&complete.document, ProjectionRequest::value_tree())
    else {
        panic!("reparsed document must project exactly");
    };
    assert_eq!(
        second.value, first.value,
        "utf-16 projection must be a materialization fixed point"
    );
}
