[package]
name = "consema"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Consema public facade"

[dependencies]
consema-core = { path = "../consema-core", version = "1.0.0-rc.1" }
consema-document = { path = "../consema-document", version = "1.0.0-rc.1" }
consema-graph = { path = "../consema-graph", version = "1.0.0-rc.1" }
consema-hcl = { path = "../consema-hcl", version = "1.0.0-rc.1" }
consema-ini = { path = "../consema-ini", version = "1.0.0-rc.1" }
consema-json = { path = "../consema-json", version = "1.0.0-rc.1" }
consema-plist = { path = "../consema-plist", version = "1.0.0-rc.1" }
consema-protocol = { path = "../consema-protocol", version = "1.0.0-rc.1" }
consema-properties = { path = "../consema-properties", version = "1.0.0-rc.1" }
consema-pvce = { path = "../consema-pvce", version = "1.0.0-rc.1" }
consema-toml = { path = "../consema-toml", version = "1.0.0-rc.1" }
consema-xml = { path = "../consema-xml", version = "1.0.0-rc.1" }
consema-yaml = { path = "../consema-yaml", version = "1.0.0-rc.1" }

[[bin]]
name = "consema"
path = "src/bin/consema/main.rs"

[lints]
workspace = true
