[package]
name = "consema-properties"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Lossless explicit-profile Java Properties implementation for Consema"

[dependencies]
consema-core = { path = "../consema-core", version = "0.7.0" }
consema-document = { path = "../consema-document", version = "0.7.0" }
encoding_rs.workspace = true

[lints]
workspace = true
