//! Canonical `xml.safe-canonical-document@1` materialization (RFC 0012 §10).
//!
//! The style consumes one fully validated `xml.element-tree@1` value and
//! creates a new `xml.1.0-safe@1` Document. It is not W3C Canonical XML and
//! does not claim C14N equivalence. The style deterministically chooses
//! declaration spelling, double-quoted attributes, generated namespace
//! prefixes, first-use namespace declaration placement, empty-element
//! spelling, reference spelling, and the requested LF/CRLF final newline.
//!
//! UTF-8, UTF-16LE, and UTF-16BE output are supported under the source
//! rules; UTF-16 output always carries its BOM. The complete tree is
//! validated before generation, the exact generated bytes are reparsed under
//! the promised Profile and encoding, and the reparsed native tree is
//! compared to the promised input semantics. Failure returns no target
//! Document and no partial output bytes.

use crate::document::{ReferenceFragment, text_semantic};
use crate::namespace::XML_NAMESPACE_URI;
use crate::{Document, XmlEncodingSelection, XmlParseLimits, XmlProfile, parse};
use consema_core::{
    AssociationLocation, AssociationRole, ObjectEntry, PortableValue, PortableValueKind, ValuePath,
    ValuePathSegment,
};
use consema_document::{
    CompleteMaterialization, FailedMaterializationAttempt, MaterializationFailure,
    MaterializationFidelity, MaterializationInputLocation, MaterializationLimits,
    MaterializationProvenanceEntry, MaterializationProvenanceMap, MaterializationRelation,
    MaterializationReport, MaterializationRequest, MaterializationResult, MaterializedOrigin,
    NewlinePolicy, NodeRef, ParseLimits, SourceEncoding, Span,
};
use std::collections::HashMap;
use std::sync::Arc;

/// Materializes one `xml.element-tree@1` record into a new canonical
/// `xml.1.0-safe@1` document.
#[must_use]
pub fn materialize(
    value: &PortableValue,
    request: &MaterializationRequest,
) -> MaterializationResult<Document> {
    let mut analyzed = Vec::new();
    match materialize_complete(value, request, &mut analyzed) {
        Ok(complete) => MaterializationResult::Complete(complete),
        Err(failure) => MaterializationResult::Failed(FailedMaterializationAttempt {
            failure,
            report: MaterializationReport::default(),
            analyzed_input_paths: analyzed,
        }),
    }
}

fn materialize_complete(
    value: &PortableValue,
    request: &MaterializationRequest,
    analyzed: &mut Vec<ValuePath>,
) -> Result<CompleteMaterialization<Document>, MaterializationFailure> {
    validate_request(request)?;
    let input = Record::validate(value, analyzed)?;
    let mut writer = Writer {
        limits: request.limits(),
        input_nodes: 0,
        output: Vec::new(),
        prefixes: PrefixTable::default(),
        scope: Vec::new(),
        items: Vec::new(),
    };
    writer.emit_document(&input, request)?;
    let text = writer.output;
    let bytes = encode_text(&text, request.encoding(), request.limits().max_output_bytes)?;
    let bytes: Arc<[u8]> = Arc::from(bytes);
    let document = parse(
        Arc::clone(&bytes),
        XmlProfile::SafeV1,
        XmlEncodingSelection::ProfileDefault,
        parse_limits(request.limits()),
    )
    .map_err(|_| MaterializationFailure::FormationFailed)?;
    if document.status() != consema_document::FormationStatus::Complete {
        return Err(MaterializationFailure::FormationFailed);
    }
    let provenance = verify_closure(&input, &document, writer.items, request.limits())?;
    Ok(CompleteMaterialization {
        document,
        fidelity: MaterializationFidelity::Exact,
        report: MaterializationReport::default(),
        provenance,
    })
}

fn validate_request(request: &MaterializationRequest) -> Result<(), MaterializationFailure> {
    if request.target_profile().id() != "xml.1.0-safe" || request.target_profile().version() != 1 {
        return Err(MaterializationFailure::UnsupportedProfile);
    }
    if request.style().id() != "xml.safe-canonical-document" || request.style().version() != 1 {
        return Err(MaterializationFailure::UnsupportedStyle);
    }
    if !matches!(
        request.encoding(),
        SourceEncoding::Utf8 | SourceEncoding::Utf16Le | SourceEncoding::Utf16Be
    ) {
        return Err(MaterializationFailure::UnsupportedEncoding);
    }
    if !matches!(request.newline(), NewlinePolicy::Lf | NewlinePolicy::CrLf) {
        return Err(MaterializationFailure::UnsupportedNewline);
    }
    Ok(())
}

const fn parse_limits(limits: MaterializationLimits) -> XmlParseLimits {
    XmlParseLimits {
        common: ParseLimits {
            max_source_bytes: limits.max_output_bytes,
            max_nesting_depth: limits.max_depth,
            max_token_count: limits.max_output_bytes,
            max_node_count: limits.max_input_nodes,
            max_diagnostics: limits.max_report_entries,
        },
        max_decoded_utf8_bytes: limits.max_output_bytes.saturating_mul(3),
        max_decoded_scalars: limits.max_output_bytes,
        max_element_count: limits.max_input_nodes,
        max_attribute_count: limits.max_input_nodes,
        max_namespace_declaration_count: limits.max_input_nodes,
        max_mixed_content_items: limits.max_input_nodes,
        max_qname_length: limits.max_output_bytes,
        max_namespace_uri_length: limits.max_output_bytes,
        max_attribute_value_length: limits.max_output_bytes,
        max_comment_length: limits.max_output_bytes,
        max_pi_length: limits.max_output_bytes,
        max_cdata_length: limits.max_output_bytes,
        max_text_length: limits.max_output_bytes,
        max_dtd_bytes: limits.max_output_bytes,
        max_entity_declarations: limits.max_input_nodes,
        max_entity_references: limits.max_input_nodes,
        max_entity_expansion_depth: limits.max_depth,
        max_expanded_entity_bytes: limits.max_output_bytes,
        max_expanded_entity_scalars: limits.max_output_bytes,
        max_entity_amplification_ratio: u64::MAX,
        max_recovery_regions: limits.max_report_entries,
    }
}

/// Encodes canonical UTF-8 text into the requested output encoding.
fn encode_text(
    text: &[u8],
    encoding: SourceEncoding,
    max_output_bytes: usize,
) -> Result<Vec<u8>, MaterializationFailure> {
    let mut output = Vec::new();
    match encoding {
        SourceEncoding::Utf8 => output.extend_from_slice(text),
        SourceEncoding::Utf16Le | SourceEncoding::Utf16Be => {
            // The writer only ever emits valid UTF-8.
            let text =
                std::str::from_utf8(text).map_err(|_| MaterializationFailure::FormationFailed)?;
            output.extend_from_slice(match encoding {
                SourceEncoding::Utf16Le => &[0xFF, 0xFE],
                _ => &[0xFE, 0xFF],
            });
            for unit in text.encode_utf16() {
                match encoding {
                    SourceEncoding::Utf16Le => output.extend_from_slice(&unit.to_le_bytes()),
                    _ => output.extend_from_slice(&unit.to_be_bytes()),
                }
            }
        }
        _ => return Err(MaterializationFailure::UnsupportedEncoding),
    }
    if output.len() > max_output_bytes {
        return Err(MaterializationFailure::ResourceLimit("output-bytes"));
    }
    Ok(output)
}

/// Validated input record mirroring `xml.element-tree@1`.
struct Record {
    declaration: Option<DeclarationRecord>,
    entities: Vec<EntityRecord>,
    root: ElementRecord,
}

struct DeclarationRecord {
    version: String,
    encoding: Option<String>,
    standalone: Option<bool>,
    path: ValuePath,
}

struct EntityRecord {
    name: String,
    replacement: String,
    path: ValuePath,
}

struct ElementRecord {
    namespace: Option<String>,
    local: String,
    namespaces: Vec<(Option<String>, String)>,
    attributes: Vec<AttributeRecord>,
    content: Vec<ContentRecord>,
    path: ValuePath,
}

struct AttributeRecord {
    namespace: Option<String>,
    local: String,
    value: String,
    path: ValuePath,
}

enum ContentRecord {
    Element(ElementRecord),
    Text {
        fragments: Vec<FragmentRecord>,
        path: ValuePath,
    },
    Cdata {
        text: String,
        path: ValuePath,
    },
    Comment {
        text: String,
        path: ValuePath,
    },
    ProcessingInstruction {
        target: String,
        content: Option<String>,
        path: ValuePath,
    },
}

enum FragmentRecord {
    Literal(String),
    CharacterReference(char),
    PredefinedEntity { name: String, resolved: String },
    GeneralEntity { name: String, resolved: String },
}

impl Record {
    fn validate(
        value: &PortableValue,
        analyzed: &mut Vec<ValuePath>,
    ) -> Result<Self, MaterializationFailure> {
        analyzed.push(ValuePath::root());
        let record = expect_string_field(value, "record", &ValuePath::root())?;
        if record != "xml.element-tree@1" {
            return Err(MaterializationFailure::InvalidRequest(
                "input record is not xml.element-tree@1",
            ));
        }
        let root_path = ValuePath::root().child(ValuePathSegment::ObjectValue("root".to_owned()));
        let root_value = expect_object_field(value, "root", &root_path)?;
        let declaration = match expect_optional_object_field(value, "declaration") {
            None => None,
            Some((declaration, path)) => {
                let version = expect_string_field(declaration, "version", &path)?;
                if version != "1.0" {
                    return Err(MaterializationFailure::Unrepresentable {
                        path: path.child(ValuePathSegment::ObjectValue("version".to_owned())),
                        kind: PortableValueKind::String,
                    });
                }
                let encoding = expect_optional_string_field(declaration, "encoding", &path)?;
                let standalone = expect_optional_boolean_field(declaration, "standalone", &path)?;
                Some(DeclarationRecord {
                    version: version.to_owned(),
                    encoding: encoding.map(str::to_owned),
                    standalone,
                    path,
                })
            }
        };
        let entities = match expect_optional_sequence_field(value, "entities")? {
            None => Vec::new(),
            Some((entities, path)) => {
                let mut out = Vec::new();
                for (index, entity) in entities.iter().enumerate() {
                    let entity_path = path.child(ValuePathSegment::SequenceElement(index as u64));
                    let name = expect_string_field(entity, "name", &entity_path)?.to_owned();
                    let replacement =
                        expect_string_field(entity, "replacement", &entity_path)?.to_owned();
                    if replacement.contains('<') {
                        return Err(MaterializationFailure::Unrepresentable {
                            path: entity_path
                                .child(ValuePathSegment::ObjectValue("replacement".to_owned())),
                            kind: PortableValueKind::String,
                        });
                    }
                    out.push(EntityRecord {
                        name,
                        replacement,
                        path: entity_path,
                    });
                }
                out
            }
        };
        let root = ElementRecord::validate(root_value, &root_path, analyzed)?;
        Ok(Self {
            declaration,
            entities,
            root,
        })
    }
}

impl ElementRecord {
    fn validate(
        value: &PortableValue,
        path: &ValuePath,
        analyzed: &mut Vec<ValuePath>,
    ) -> Result<Self, MaterializationFailure> {
        analyzed.push(path.clone());
        let (namespace, local) = expect_expanded_name(value, path)?;
        let namespaces = match expect_optional_sequence_field(value, "namespaces")? {
            None => Vec::new(),
            Some((bindings, bindings_path)) => {
                let mut out = Vec::new();
                for (index, binding) in bindings.iter().enumerate() {
                    let binding_path =
                        bindings_path.child(ValuePathSegment::SequenceElement(index as u64));
                    let prefix = expect_optional_string_field(binding, "prefix", &binding_path)?;
                    let uri = expect_string_field(binding, "uri", &binding_path)?.to_owned();
                    out.push((prefix.map(str::to_owned), uri));
                }
                out
            }
        };
        let attributes = match expect_optional_sequence_field(value, "attributes")? {
            None => Vec::new(),
            Some((attributes, attributes_path)) => {
                let mut out = Vec::new();
                for (index, attribute) in attributes.iter().enumerate() {
                    let attribute_path =
                        attributes_path.child(ValuePathSegment::SequenceElement(index as u64));
                    let (attr_namespace, attr_local) =
                        expect_expanded_name(attribute, &attribute_path)?;
                    let value_text =
                        expect_string_field(attribute, "value", &attribute_path)?.to_owned();
                    out.push(AttributeRecord {
                        namespace: attr_namespace,
                        local: attr_local,
                        value: value_text,
                        path: attribute_path,
                    });
                }
                out
            }
        };
        let content = match expect_optional_sequence_field(value, "content")? {
            None => Vec::new(),
            Some((content, content_path)) => {
                let mut out = Vec::new();
                for (index, item) in content.iter().enumerate() {
                    let item_path =
                        content_path.child(ValuePathSegment::SequenceElement(index as u64));
                    if item.kind() == PortableValueKind::Object
                        && item.as_object().is_some_and(|object| {
                            object.iter().any(|entry| entry.key() == "expanded-name")
                        })
                    {
                        out.push(ContentRecord::Element(ElementRecord::validate(
                            item, &item_path, analyzed,
                        )?));
                        continue;
                    }
                    let kind = expect_string_field(item, "kind", &item_path)?;
                    match kind {
                        "text" => {
                            let fragments_path = item_path
                                .child(ValuePathSegment::ObjectValue("fragments".to_owned()));
                            let fragments_value =
                                expect_object_field(item, "fragments", &fragments_path)?;
                            let fragments_sequence =
                                fragments_value.as_sequence().ok_or_else(|| {
                                    MaterializationFailure::Unrepresentable {
                                        path: fragments_path.clone(),
                                        kind: fragments_value.kind(),
                                    }
                                })?;
                            let mut fragments = Vec::new();
                            for (fragment_index, fragment) in fragments_sequence.iter().enumerate()
                            {
                                let fragment_path = fragments_path.child(
                                    ValuePathSegment::SequenceElement(fragment_index as u64),
                                );
                                let fragment_kind =
                                    expect_string_field(fragment, "kind", &fragment_path)?;
                                let fragment = match fragment_kind {
                                    "literal" => FragmentRecord::Literal(
                                        expect_string_field(fragment, "text", &fragment_path)?
                                            .to_owned(),
                                    ),
                                    "character-reference" => {
                                        let resolved = expect_string_field(
                                            fragment,
                                            "resolved",
                                            &fragment_path,
                                        )?;
                                        let mut chars = resolved.chars();
                                        let (Some(first), None) = (chars.next(), chars.next())
                                        else {
                                            return Err(MaterializationFailure::Unrepresentable {
                                                path: fragment_path,
                                                kind: PortableValueKind::String,
                                            });
                                        };
                                        FragmentRecord::CharacterReference(first)
                                    }
                                    "predefined-entity" => FragmentRecord::PredefinedEntity {
                                        name: expect_string_field(
                                            fragment,
                                            "name",
                                            &fragment_path,
                                        )?
                                        .to_owned(),
                                        resolved: expect_string_field(
                                            fragment,
                                            "resolved",
                                            &fragment_path,
                                        )?
                                        .to_owned(),
                                    },
                                    "general-entity" => FragmentRecord::GeneralEntity {
                                        name: expect_string_field(
                                            fragment,
                                            "name",
                                            &fragment_path,
                                        )?
                                        .to_owned(),
                                        resolved: expect_string_field(
                                            fragment,
                                            "resolved",
                                            &fragment_path,
                                        )?
                                        .to_owned(),
                                    },
                                    _ => {
                                        return Err(MaterializationFailure::Unrepresentable {
                                            path: fragment_path,
                                            kind: fragment.kind(),
                                        });
                                    }
                                };
                                fragments.push(fragment);
                            }
                            out.push(ContentRecord::Text {
                                fragments,
                                path: item_path,
                            });
                        }
                        "cdata" => out.push(ContentRecord::Cdata {
                            text: expect_string_field(item, "text", &item_path)?.to_owned(),
                            path: item_path,
                        }),
                        "comment" => out.push(ContentRecord::Comment {
                            text: expect_string_field(item, "text", &item_path)?.to_owned(),
                            path: item_path,
                        }),
                        "processing-instruction" => {
                            let target =
                                expect_string_field(item, "target", &item_path)?.to_owned();
                            let content =
                                expect_optional_string_field(item, "content", &item_path)?
                                    .map(str::to_owned);
                            out.push(ContentRecord::ProcessingInstruction {
                                target,
                                content,
                                path: item_path,
                            });
                        }
                        _ => {
                            return Err(MaterializationFailure::Unrepresentable {
                                path: item_path,
                                kind: item.kind(),
                            });
                        }
                    }
                }
                out
            }
        };
        let mut names: Vec<(Option<String>, String)> = Vec::new();
        for attribute in &attributes {
            if names.contains(&(attribute.namespace.clone(), attribute.local.clone())) {
                return Err(MaterializationFailure::InvalidRequest(
                    "duplicate expanded attribute in input record",
                ));
            }
            names.push((attribute.namespace.clone(), attribute.local.clone()));
        }
        Ok(Self {
            namespace,
            local,
            namespaces,
            attributes,
            content,
            path: path.clone(),
        })
    }
}

/// Deterministic generated-prefix assignment by first-encounter order.
#[derive(Default)]
struct PrefixTable {
    /// URI to generated prefix, excluding the default namespace and `xml`.
    entries: HashMap<String, String>,
    next: usize,
}

impl PrefixTable {
    fn prefix_for(&mut self, namespace: &str, default: Option<&str>) -> String {
        if Some(namespace) == default {
            return String::new();
        }
        if namespace == XML_NAMESPACE_URI {
            return "xml".to_owned();
        }
        if let Some(prefix) = self.entries.get(namespace) {
            return prefix.clone();
        }
        self.next += 1;
        let prefix = format!("ns{}", self.next);
        self.entries.insert(namespace.to_owned(), prefix.clone());
        prefix
    }
}

/// One input location recorded during generation, paired by order with the
/// reparsed document during closure verification.
enum InputItem {
    Declaration(ValuePath),
    Entity(ValuePath),
    Element(ValuePath),
    NamespaceBinding(ValuePath),
    Attribute(ValuePath),
    Text(ValuePath),
    Fragment(ValuePath),
    Cdata(ValuePath),
    Comment(ValuePath),
    ProcessingInstruction(ValuePath),
}

impl InputItem {
    fn location(&self) -> MaterializationInputLocation {
        match self {
            Self::Declaration(path)
            | Self::Entity(path)
            | Self::Element(path)
            | Self::Attribute(path)
            | Self::Text(path)
            | Self::Fragment(path)
            | Self::Cdata(path)
            | Self::Comment(path)
            | Self::ProcessingInstruction(path) => {
                MaterializationInputLocation::Value(path.clone())
            }
            // A generated binding derives from the element's expanded name.
            Self::NamespaceBinding(path) => MaterializationInputLocation::Association(
                AssociationLocation::new(path.clone(), 0, AssociationRole::ObjectEntry),
            ),
        }
    }
}

struct Writer {
    limits: MaterializationLimits,
    input_nodes: usize,
    output: Vec<u8>,
    prefixes: PrefixTable,
    /// In-scope bindings as `(prefix, uri)` with `None` the default
    /// namespace; restored by truncation when an element exits.
    scope: Vec<(Option<String>, String)>,
    items: Vec<InputItem>,
}

impl Writer {
    fn step(&mut self) -> Result<(), MaterializationFailure> {
        self.input_nodes = self
            .input_nodes
            .checked_add(1)
            .ok_or(MaterializationFailure::ResourceLimit("input-nodes"))?;
        if self.input_nodes > self.limits.max_input_nodes {
            return Err(MaterializationFailure::ResourceLimit("input-nodes"));
        }
        Ok(())
    }

    fn push(&mut self, bytes: &[u8]) -> Result<(), MaterializationFailure> {
        self.output.extend_from_slice(bytes);
        if self.output.len() > self.limits.max_output_bytes {
            return Err(MaterializationFailure::ResourceLimit("output-bytes"));
        }
        Ok(())
    }

    /// Spelling prefix for one expanded namespace, using the current scope.
    ///
    /// `Some("")` means unprefixed (the default namespace applies, or no
    /// namespace); `Some(prefix)` is a prefixed spelling; `None` means the
    /// URI is not bound in scope and a declaration must be generated.
    fn spelling_prefix(&self, uri: Option<&str>) -> Option<String> {
        match uri {
            None => Some(String::new()),
            Some(uri) if uri == XML_NAMESPACE_URI => Some("xml".to_owned()),
            Some(uri) => {
                if self
                    .scope
                    .iter()
                    .rev()
                    .any(|(prefix, bound)| prefix.is_none() && bound == uri)
                {
                    return Some(String::new());
                }
                self.scope
                    .iter()
                    .rev()
                    .find(|(prefix, bound)| prefix.is_some() && bound == uri)
                    .and_then(|(prefix, _)| prefix.clone())
            }
        }
    }

    fn push_escaped_text(&mut self, text: &str) -> Result<(), MaterializationFailure> {
        let mut rest = text;
        while let Some(at) = rest.find(['&', '<']) {
            self.push(&rest.as_bytes()[..at])?;
            match rest.as_bytes()[at] {
                b'&' => self.push(b"&amp;")?,
                _ => self.push(b"&lt;")?,
            }
            rest = &rest[at + 1..];
        }
        self.push(rest.as_bytes())
    }

    fn push_escaped_attribute(&mut self, text: &str) -> Result<(), MaterializationFailure> {
        let mut rest = text;
        while let Some(at) = rest.find(['&', '<', '"']) {
            self.push(&rest.as_bytes()[..at])?;
            match rest.as_bytes()[at] {
                b'&' => self.push(b"&amp;")?,
                b'<' => self.push(b"&lt;")?,
                _ => self.push(b"&quot;")?,
            }
            rest = &rest[at + 1..];
        }
        self.push(rest.as_bytes())
    }

    fn emit_document(
        &mut self,
        input: &Record,
        request: &MaterializationRequest,
    ) -> Result<(), MaterializationFailure> {
        self.step()?;
        if let Some(declaration) = &input.declaration {
            self.items
                .push(InputItem::Declaration(declaration.path.clone()));
            self.push(b"<?xml version=\"")?;
            self.push_escaped_attribute(&declaration.version)?;
            self.push(b"\"")?;
            let declared_encoding = declaration.encoding.clone().or_else(|| {
                if matches!(
                    request.encoding(),
                    SourceEncoding::Utf16Le | SourceEncoding::Utf16Be
                ) {
                    Some("UTF-16".to_owned())
                } else {
                    None
                }
            });
            if let Some(encoding) = declared_encoding {
                self.push(b" encoding=\"")?;
                self.push_escaped_attribute(&encoding)?;
                self.push(b"\"")?;
            }
            if let Some(standalone) = declaration.standalone {
                self.push(if standalone {
                    b" standalone=\"yes\""
                } else {
                    b" standalone=\"no\""
                })?;
            }
            self.push(b"?>")?;
        }
        if !input.entities.is_empty() {
            self.push(b"<!DOCTYPE ")?;
            let doctype_name = match self.spelling_prefix(input.root.namespace.as_deref()) {
                Some(prefix) if prefix.is_empty() => input.root.local.clone(),
                Some(prefix) => format!("{prefix}:{}", input.root.local),
                None => {
                    // An unbound root namespace cannot be named in the
                    // DOCTYPE without a declaration; fail honestly.
                    return Err(MaterializationFailure::Unrepresentable {
                        path: input.root.path.clone(),
                        kind: PortableValueKind::Object,
                    });
                }
            };
            self.push(doctype_name.as_bytes())?;
            self.push(b" [")?;
            for entity in &input.entities {
                self.items.push(InputItem::Entity(entity.path.clone()));
                self.push(b"<!ENTITY ")?;
                self.push(entity.name.as_bytes())?;
                self.push(b" \"")?;
                self.push_escaped_attribute(&entity.replacement)?;
                self.push(b"\">")?;
            }
            self.push(b"]>")?;
        }
        self.emit_element(&input.root, 0)?;
        self.push(request.newline().bytes())?;
        Ok(())
    }

    fn emit_element(
        &mut self,
        element: &ElementRecord,
        depth: usize,
    ) -> Result<(), MaterializationFailure> {
        self.step()?;
        if depth > self.limits.max_depth {
            return Err(MaterializationFailure::ResourceLimit("input-depth"));
        }
        self.items.push(InputItem::Element(element.path.clone()));
        let scope_len = self.scope.len();
        // The record's namespace declarations are reproduced verbatim in
        // order; the spelling of names follows the resulting scope.
        for (prefix, uri) in &element.namespaces {
            self.scope.push((prefix.clone(), uri.clone()));
        }
        let element_prefix =
            if let Some(prefix) = self.spelling_prefix(element.namespace.as_deref()) {
                prefix
            } else {
                // Unbound URI in a hand-built record: declare a generated
                // default namespace on this element.
                let uri = element.namespace.as_deref().unwrap_or(XML_NAMESPACE_URI);
                if uri == XML_NAMESPACE_URI {
                    "xml".to_owned()
                } else {
                    self.push(b"<")?;
                    self.push(element.local.as_bytes())?;
                    self.push(b" xmlns=\"")?;
                    self.push_escaped_attribute(uri)?;
                    self.push(b"\"")?;
                    self.scope.push((None, uri.to_owned()));
                    self.items
                        .push(InputItem::NamespaceBinding(element.path.clone()));
                    String::new()
                }
            };
        self.push(b"<")?;
        if element_prefix.is_empty() {
            self.push(element.local.as_bytes())?;
        } else {
            self.push(element_prefix.as_bytes())?;
            self.push(b":")?;
            self.push(element.local.as_bytes())?;
        }
        for (prefix, uri) in &element.namespaces {
            self.items
                .push(InputItem::NamespaceBinding(element.path.clone()));
            if let Some(prefix) = prefix {
                self.push(b" xmlns:")?;
                self.push(prefix.as_bytes())?;
                self.push(b"=\"")?;
                self.push_escaped_attribute(uri)?;
                self.push(b"\"")?;
            } else {
                self.push(b" xmlns=\"")?;
                self.push_escaped_attribute(uri)?;
                self.push(b"\"")?;
            }
        }
        for attribute in &element.attributes {
            self.items
                .push(InputItem::Attribute(attribute.path.clone()));
            let attribute_prefix =
                if let Some(prefix) = self.spelling_prefix(attribute.namespace.as_deref()) {
                    prefix
                } else {
                    // Unbound attribute namespace: declare a generated
                    // prefix on this element.
                    let uri = attribute.namespace.as_deref().unwrap_or(XML_NAMESPACE_URI);
                    let generated = self.prefixes.prefix_for(uri, None);
                    self.push(b" xmlns:")?;
                    self.push(generated.as_bytes())?;
                    self.push(b"=\"")?;
                    self.push_escaped_attribute(uri)?;
                    self.push(b"\"")?;
                    self.scope.push((Some(generated.clone()), uri.to_owned()));
                    self.items
                        .push(InputItem::NamespaceBinding(element.path.clone()));
                    generated
                };
            self.push(b" ")?;
            if attribute_prefix.is_empty() {
                self.push(attribute.local.as_bytes())?;
            } else {
                self.push(attribute_prefix.as_bytes())?;
                self.push(b":")?;
                self.push(attribute.local.as_bytes())?;
            }
            self.push(b"=\"")?;
            self.push_escaped_attribute(&attribute.value)?;
            self.push(b"\"")?;
        }
        if element.content.is_empty() {
            self.push(b"/>")?;
            self.scope.truncate(scope_len);
            return Ok(());
        }
        self.push(b">")?;
        for item in &element.content {
            match item {
                ContentRecord::Element(child) => {
                    self.emit_element(child, depth + 1)?;
                }
                ContentRecord::Text { fragments, path } => {
                    self.items.push(InputItem::Text(path.clone()));
                    for fragment in fragments {
                        self.items.push(InputItem::Fragment(path.clone()));
                        match fragment {
                            FragmentRecord::Literal(text) => self.push_escaped_text(text)?,
                            FragmentRecord::CharacterReference(resolved) => {
                                self.push(format!("&#{};", *resolved as u32).as_bytes())?;
                            }
                            FragmentRecord::PredefinedEntity { name, .. }
                            | FragmentRecord::GeneralEntity { name, .. } => {
                                self.push(b"&")?;
                                self.push(name.as_bytes())?;
                                self.push(b";")?;
                            }
                        }
                    }
                }
                ContentRecord::Cdata { text, path } => {
                    self.items.push(InputItem::Cdata(path.clone()));
                    if text.contains("]]>") {
                        return Err(MaterializationFailure::Unrepresentable {
                            path: path.clone(),
                            kind: PortableValueKind::String,
                        });
                    }
                    self.push(b"<![CDATA[")?;
                    self.push(text.as_bytes())?;
                    self.push(b"]]>")?;
                }
                ContentRecord::Comment { text, path } => {
                    self.items.push(InputItem::Comment(path.clone()));
                    if text.contains("--") || text.ends_with('-') {
                        return Err(MaterializationFailure::Unrepresentable {
                            path: path.clone(),
                            kind: PortableValueKind::String,
                        });
                    }
                    self.push(b"<!--")?;
                    self.push(text.as_bytes())?;
                    self.push(b"-->")?;
                }
                ContentRecord::ProcessingInstruction {
                    target,
                    content,
                    path,
                } => {
                    self.items
                        .push(InputItem::ProcessingInstruction(path.clone()));
                    if target.eq_ignore_ascii_case("xml")
                        || content.as_deref().is_some_and(|c| c.contains("?>"))
                    {
                        return Err(MaterializationFailure::Unrepresentable {
                            path: path.clone(),
                            kind: PortableValueKind::String,
                        });
                    }
                    self.push(b"<?")?;
                    self.push(target.as_bytes())?;
                    if let Some(content) = content {
                        self.push(b" ")?;
                        self.push(content.as_bytes())?;
                    }
                    self.push(b"?>")?;
                }
            }
        }
        self.push(b"</")?;
        if element_prefix.is_empty() {
            self.push(element.local.as_bytes())?;
        } else {
            self.push(element_prefix.as_bytes())?;
            self.push(b":")?;
            self.push(element.local.as_bytes())?;
        }
        self.push(b">")?;
        self.scope.truncate(scope_len);
        Ok(())
    }
}

/// One matched output origin in the reparsed document.
struct OutputItem {
    node: NodeRef,
    span: Span,
    relation: MaterializationRelation,
}

/// Walks the input record and the reparsed document in lockstep, compares
/// the promised semantics, and pairs every recorded input location with its
/// exact output origin. Any mismatch fails the whole materialization.
fn verify_closure(
    input: &Record,
    document: &Document,
    items: Vec<InputItem>,
    limits: MaterializationLimits,
) -> Result<MaterializationProvenanceMap, MaterializationFailure> {
    let mut outputs = Vec::new();
    let root = document
        .root()
        .ok_or(MaterializationFailure::FormationFailed)?;
    // Declaration closure.
    match (&input.declaration, document.declaration()) {
        (None, None) => {}
        (Some(declared), Some(reparsed)) => {
            if reparsed.version.as_ref() != declared.version
                || reparsed.standalone.map(|(_, value)| value) != declared.standalone
            {
                return Err(MaterializationFailure::FormationFailed);
            }
        }
        _ => return Err(MaterializationFailure::FormationFailed),
    }
    // Entity closure.
    match (&input.entities, document.doctype()) {
        (entities, Some(doctype)) => {
            if doctype.entities.len() != entities.len()
                || doctype
                    .entities
                    .iter()
                    .zip(entities)
                    .any(|(reparsed, declared)| {
                        reparsed.name.as_ref() != declared.name
                            || reparsed.replacement.as_ref() != declared.replacement
                    })
            {
                return Err(MaterializationFailure::FormationFailed);
            }
        }
        (entities, None) => {
            if !entities.is_empty() {
                return Err(MaterializationFailure::FormationFailed);
            }
        }
    }
    // Declaration and entity outputs precede the tree walk, matching the
    // generation order of their input items.
    if input.declaration.is_some() {
        let span = document
            .declaration()
            .map(|declaration| declaration.span)
            .ok_or(MaterializationFailure::FormationFailed)?;
        outputs.push(OutputItem {
            node: document
                .authority()
                .node_ref(0, consema_document::NodeRole::XmlDeclaration),
            span,
            relation: MaterializationRelation::Direct,
        });
    }
    if let Some(doctype) = document.doctype() {
        for entity in doctype.entities.iter() {
            outputs.push(OutputItem {
                node: document
                    .authority()
                    .node_ref(0, consema_document::NodeRole::XmlDoctype),
                span: entity.span,
                relation: MaterializationRelation::Direct,
            });
        }
    }
    let mut context = ClosureContext {
        document,
        outputs: &mut outputs,
        limits,
    };
    context.element(&input.root, root)?;
    // Pair input items with outputs by traversal order; adjacent items with
    // the same input location share one provenance entry.
    if outputs.len() != items.len() {
        return Err(MaterializationFailure::FormationFailed);
    }
    let mut entries: Vec<MaterializationProvenanceEntry> = Vec::new();
    for (item, output) in items.into_iter().zip(outputs) {
        let location = item.location();
        let origin = MaterializedOrigin {
            snapshot: document.snapshot_identity(),
            node: output.node,
            span: output.span,
            relation: output.relation,
        };
        if let Some(last) = entries.last_mut() {
            if last.input == location {
                last.outputs.push(origin);
                continue;
            }
        }
        entries.push(MaterializationProvenanceEntry {
            input: location,
            outputs: vec![origin],
        });
    }
    MaterializationProvenanceMap::new(entries, document.snapshot_identity(), limits)
}

struct ClosureContext<'a> {
    document: &'a Document,
    outputs: &'a mut Vec<OutputItem>,
    limits: MaterializationLimits,
}

impl ClosureContext<'_> {
    fn push(
        &mut self,
        node: NodeRef,
        span: Span,
        relation: MaterializationRelation,
    ) -> Result<(), MaterializationFailure> {
        if self.outputs.len() >= self.limits.max_provenance_entries {
            return Err(MaterializationFailure::ResourceLimit("provenance-entries"));
        }
        self.outputs.push(OutputItem {
            node,
            span,
            relation,
        });
        Ok(())
    }

    fn element(
        &mut self,
        input: &ElementRecord,
        element: crate::XmlElement<'_>,
    ) -> Result<(), MaterializationFailure> {
        self.push(
            element.node_ref(),
            element.span(),
            MaterializationRelation::Direct,
        )?;
        let expanded = element
            .expanded()
            .ok_or(MaterializationFailure::FormationFailed)?;
        let matches = match (input.namespace.as_deref(), expanded.namespace.as_deref()) {
            (Some(a), Some(b)) => a == b,
            (None, None) => true,
            _ => false,
        };
        if !matches || expanded.local.as_ref() != input.local {
            return Err(MaterializationFailure::FormationFailed);
        }
        for binding in element.namespace_bindings() {
            self.push(
                self.document.authority().node_ref(
                    binding.ordinal,
                    consema_document::NodeRole::XmlNamespaceBinding,
                ),
                binding.span,
                MaterializationRelation::Generated,
            )?;
        }
        let attributes = element.attributes();
        if attributes.len() != input.attributes.len() {
            return Err(MaterializationFailure::FormationFailed);
        }
        for (input_attribute, attribute) in input.attributes.iter().zip(attributes) {
            self.push(
                self.document
                    .authority()
                    .node_ref(attribute.ordinal, consema_document::NodeRole::XmlAttribute),
                attribute.span,
                MaterializationRelation::Direct,
            )?;
            let expanded = attribute
                .expanded
                .as_ref()
                .ok_or(MaterializationFailure::FormationFailed)?;
            let name_matches = match (
                input_attribute.namespace.as_deref(),
                expanded.namespace.as_deref(),
            ) {
                (Some(a), Some(b)) => a == b,
                (None, None) => true,
                _ => false,
            };
            if !name_matches
                || expanded.local.as_ref() != input_attribute.local
                || attribute.normalized_value.as_ref() != input_attribute.value
            {
                return Err(MaterializationFailure::FormationFailed);
            }
        }
        let children: Vec<_> = element.children().collect();
        let input_content: Vec<&ContentRecord> = input.content.iter().collect();
        if children.len() != input_content.len() {
            return Err(MaterializationFailure::FormationFailed);
        }
        for (child, input_item) in children.iter().zip(input_content) {
            match (child.element(), input_item) {
                (Some(child_element), ContentRecord::Element(input_element)) => {
                    self.element(input_element, child_element)?;
                }
                (None, ContentRecord::Text { fragments, .. }) => {
                    let text = child
                        .text()
                        .ok_or(MaterializationFailure::FormationFailed)?;
                    self.push(
                        self.document
                            .authority()
                            .node_ref(text.ordinal, consema_document::NodeRole::XmlText),
                        text.span,
                        MaterializationRelation::Direct,
                    )?;
                    let mut semantic = String::new();
                    for fragment in fragments {
                        match fragment {
                            FragmentRecord::Literal(text) => {
                                push_normalized(&mut semantic, text);
                            }
                            FragmentRecord::CharacterReference(resolved) => {
                                semantic.push(*resolved);
                            }
                            FragmentRecord::PredefinedEntity { resolved, .. }
                            | FragmentRecord::GeneralEntity { resolved, .. } => {
                                push_normalized(&mut semantic, resolved);
                            }
                        }
                        self.push(
                            self.document.authority().node_ref(
                                text.ordinal,
                                consema_document::NodeRole::XmlEntityReference,
                            ),
                            text.fragments
                                .first()
                                .map_or(text.span, ReferenceFragment::span),
                            MaterializationRelation::Direct,
                        )?;
                    }
                    if text_semantic(text) != semantic {
                        return Err(MaterializationFailure::FormationFailed);
                    }
                }
                (None, ContentRecord::Cdata { text, .. }) => {
                    let cdata = child
                        .cdata()
                        .ok_or(MaterializationFailure::FormationFailed)?;
                    self.push(
                        self.document
                            .authority()
                            .node_ref(cdata.ordinal, consema_document::NodeRole::XmlCdata),
                        cdata.span,
                        MaterializationRelation::Direct,
                    )?;
                    if cdata.text.as_ref() != text {
                        return Err(MaterializationFailure::FormationFailed);
                    }
                }
                (None, ContentRecord::Comment { text, .. }) => {
                    let comment = child
                        .comment()
                        .ok_or(MaterializationFailure::FormationFailed)?;
                    self.push(
                        self.document
                            .authority()
                            .node_ref(comment.ordinal, consema_document::NodeRole::XmlComment),
                        comment.span,
                        MaterializationRelation::Direct,
                    )?;
                    if comment.text.as_ref() != text {
                        return Err(MaterializationFailure::FormationFailed);
                    }
                }
                (
                    None,
                    ContentRecord::ProcessingInstruction {
                        target, content, ..
                    },
                ) => {
                    let pi = child
                        .processing_instruction()
                        .ok_or(MaterializationFailure::FormationFailed)?;
                    self.push(
                        self.document.authority().node_ref(
                            pi.ordinal,
                            consema_document::NodeRole::XmlProcessingInstruction,
                        ),
                        pi.span,
                        MaterializationRelation::Direct,
                    )?;
                    if pi.target.as_ref() != target
                        || pi.content.as_ref().map(|(_, text)| text.as_ref()) != content.as_deref()
                    {
                        return Err(MaterializationFailure::FormationFailed);
                    }
                }
                _ => return Err(MaterializationFailure::FormationFailed),
            }
        }
        Ok(())
    }
}

/// XML 1.0 line-end normalization for one fragment: CRLF and CR become LF.
fn push_normalized(out: &mut String, text: &str) {
    let mut chars = text.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '\r' => {
                out.push('\n');
                if chars.peek() == Some(&'\n') {
                    chars.next();
                }
            }
            _ => out.push(c),
        }
    }
}

/// Looks up one object entry by exact key.
fn object_field<'v>(
    object: &'v [consema_core::ObjectEntry],
    name: &str,
) -> Option<&'v PortableValue> {
    object
        .iter()
        .find(|entry| entry.key() == name)
        .map(ObjectEntry::value)
}

fn expect_object_field<'v>(
    value: &'v PortableValue,
    name: &str,
    path: &ValuePath,
) -> Result<&'v PortableValue, MaterializationFailure> {
    let object = value
        .as_object()
        .ok_or_else(|| MaterializationFailure::Unrepresentable {
            path: path.clone(),
            kind: value.kind(),
        })?;
    let Some(field) = object_field(object, name) else {
        return Err(MaterializationFailure::InvalidRequest(
            "missing record field",
        ));
    };
    Ok(field)
}

fn expect_optional_object_field<'v>(
    value: &'v PortableValue,
    name: &str,
) -> Option<(&'v PortableValue, ValuePath)> {
    let object = value.as_object()?;
    let field = object_field(object, name)?;
    let path = ValuePath::root().child(ValuePathSegment::ObjectValue(name.to_owned()));
    Some((field, path))
}

fn expect_string_field<'v>(
    value: &'v PortableValue,
    name: &str,
    path: &ValuePath,
) -> Result<&'v str, MaterializationFailure> {
    let object = value
        .as_object()
        .ok_or_else(|| MaterializationFailure::Unrepresentable {
            path: path.clone(),
            kind: value.kind(),
        })?;
    let Some(field) = object_field(object, name) else {
        return Err(MaterializationFailure::InvalidRequest(
            "missing record field",
        ));
    };
    field
        .as_string()
        .ok_or_else(|| MaterializationFailure::Unrepresentable {
            path: path.child(ValuePathSegment::ObjectValue(name.to_owned())),
            kind: field.kind(),
        })
}

fn expect_optional_string_field<'v>(
    value: &'v PortableValue,
    name: &str,
    path: &ValuePath,
) -> Result<Option<&'v str>, MaterializationFailure> {
    let Some(object) = value.as_object() else {
        return Ok(None);
    };
    let Some(field) = object_field(object, name) else {
        return Ok(None);
    };
    if field.kind() == PortableValueKind::Null {
        return Ok(None);
    }
    Ok(Some(field.as_string().ok_or_else(|| {
        MaterializationFailure::Unrepresentable {
            path: path.child(ValuePathSegment::ObjectValue(name.to_owned())),
            kind: field.kind(),
        }
    })?))
}

fn expect_optional_boolean_field(
    value: &PortableValue,
    name: &str,
    path: &ValuePath,
) -> Result<Option<bool>, MaterializationFailure> {
    let Some(object) = value.as_object() else {
        return Ok(None);
    };
    let Some(field) = object_field(object, name) else {
        return Ok(None);
    };
    if field.kind() == PortableValueKind::Null {
        return Ok(None);
    }
    Ok(Some(field.as_boolean().ok_or_else(|| {
        MaterializationFailure::Unrepresentable {
            path: path.child(ValuePathSegment::ObjectValue(name.to_owned())),
            kind: field.kind(),
        }
    })?))
}

fn expect_optional_sequence_field<'v>(
    value: &'v PortableValue,
    name: &str,
) -> Result<Option<(&'v [PortableValue], ValuePath)>, MaterializationFailure> {
    let Some(object) = value.as_object() else {
        return Ok(None);
    };
    let Some(field) = object_field(object, name) else {
        return Ok(None);
    };
    let path = ValuePath::root().child(ValuePathSegment::ObjectValue(name.to_owned()));
    let Some(sequence) = field.as_sequence() else {
        return Err(MaterializationFailure::Unrepresentable {
            path,
            kind: field.kind(),
        });
    };
    Ok(Some((sequence, path)))
}

/// Reads an expanded-name object `{ "namespace": string|null, "local": string }`.
fn expect_expanded_name(
    value: &PortableValue,
    path: &ValuePath,
) -> Result<(Option<String>, String), MaterializationFailure> {
    let name_path = path.child(ValuePathSegment::ObjectValue("expanded-name".to_owned()));
    let name = expect_object_field(value, "expanded-name", &name_path)?;
    let namespace = expect_optional_string_field(name, "namespace", &name_path)?.map(str::to_owned);
    let local = expect_string_field(name, "local", &name_path)?.to_owned();
    Ok((namespace, local))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::projection::ProjectionRequest;
    use crate::{ProjectionResult, XmlEncodingSelection, XmlParseLimits, XmlProfile};
    use consema_core::ObjectBuilder;
    use consema_document::{MaterializationRequest, MaterializationStyleId, ProfileId};
    use std::sync::Arc;

    fn request() -> MaterializationRequest {
        MaterializationRequest::new(
            ProfileId::new("xml.1.0-safe", 1),
            MaterializationStyleId::new("xml.safe-canonical-document", 1),
        )
    }

    fn project(source: &[u8]) -> PortableValue {
        let bytes: Arc<[u8]> = Arc::from(source);
        let document = parse(
            bytes,
            XmlProfile::SafeV1,
            XmlEncodingSelection::ProfileDefault,
            XmlParseLimits::default(),
        )
        .expect("forms");
        assert_eq!(
            document.status(),
            consema_document::FormationStatus::Complete
        );
        let ProjectionResult::Complete(projection) =
            document.project(ProjectionRequest::element_tree())
        else {
            panic!("exact projection");
        };
        projection.value
    }

    fn round_trip(source: &[u8]) -> Document {
        let value = project(source);
        match materialize(&value, &request()) {
            MaterializationResult::Complete(complete) => complete.document,
            MaterializationResult::Failed(failed) => {
                panic!("round trip must materialize: {:?}", failed.failure);
            }
        }
    }

    #[test]
    fn compact_document_round_trips_the_projection() {
        let document = round_trip(br#"<root a="1"><child>t</child></root>"#);
        assert_eq!(
            document.status(),
            consema_document::FormationStatus::Complete
        );
        assert_eq!(
            document.render(),
            br#"<root a="1"><child>t</child></root>
"#
            .as_slice()
        );
    }

    #[test]
    fn namespace_documents_reproduce_the_record_bindings() {
        let document = round_trip(br#"<s:root xmlns:s="urn:svc"><s:child/></s:root>"#);
        assert_eq!(
            document.render(),
            br#"<s:root xmlns:s="urn:svc"><s:child/></s:root>
"#
            .as_slice(),
            "the record's own namespace strategy is reproduced verbatim"
        );
        let document = round_trip(br#"<root xmlns:a="urn:a"><a:x/><b:x xmlns:b="urn:b"/></root>"#);
        assert_eq!(
            document.render(),
            br#"<root xmlns:a="urn:a"><a:x/><b:x xmlns:b="urn:b"/></root>
"#
            .as_slice()
        );
    }

    #[test]
    fn mixed_content_and_references_round_trip() {
        let document =
            round_trip(br"<root>a &lt; b &amp; c &#65;<![CDATA[raw]]><!--ok--><?pi v?></root>");
        // The canonical output is fully deterministic, including the final
        // LF; the reference spellings and literal escapes are exact.
        assert_eq!(
            document.render(),
            br"<root>a &lt; b &amp; c &#65;<![CDATA[raw]]><!--ok--><?pi v?></root>
"
            .as_slice()
        );
    }

    #[test]
    fn internal_entities_round_trip_with_doctype() {
        let document =
            round_trip(br#"<!DOCTYPE root [<!ENTITY greeting "hello">]><root>&greeting;</root>"#);
        assert_eq!(
            document.render(),
            br#"<!DOCTYPE root [<!ENTITY greeting "hello">]><root>&greeting;</root>
"#
            .as_slice()
        );
    }

    #[test]
    fn crlf_newline_is_honored() {
        let value = project(br"<root/>");
        let request = request().with_newline(NewlinePolicy::CrLf);
        match materialize(&value, &request) {
            MaterializationResult::Complete(complete) => {
                assert_eq!(complete.document.render(), b"<root/>\r\n");
                assert_eq!(complete.fidelity, MaterializationFidelity::Exact);
            }
            MaterializationResult::Failed(failed) => {
                panic!("must materialize: {:?}", failed.failure);
            }
        }
    }

    #[test]
    fn utf16le_output_carries_bom() {
        let value = project("<root>中文</root>".as_bytes());
        let request = request().with_encoding(SourceEncoding::Utf16Le);
        let MaterializationResult::Complete(complete) = materialize(&value, &request) else {
            panic!("must materialize");
        };
        let bytes = complete.document.render();
        assert_eq!(&bytes[..2], &[0xFF, 0xFE], "UTF-16LE BOM");
        assert_eq!(bytes.len() % 2, 0);
        assert_eq!(complete.fidelity, MaterializationFidelity::Exact);
    }

    #[test]
    fn invalid_record_is_rejected() {
        let mut builder = consema_core::ObjectBuilder::new();
        builder
            .insert("record", PortableValue::string("xml.something-else@1"))
            .expect("insert");
        let value = builder.build();
        match materialize(&value, &request()) {
            MaterializationResult::Failed(attempt) => {
                assert!(
                    matches!(attempt.failure, MaterializationFailure::InvalidRequest(_)),
                    "wrong record must fail as InvalidRequest, got {:?}",
                    attempt.failure
                );
                assert!(
                    !attempt.analyzed_input_paths.is_empty(),
                    "the record path is analyzed before rejection"
                );
            }
            MaterializationResult::Complete(_) => panic!("must fail"),
        }
    }

    #[test]
    fn wrong_profile_or_style_is_rejected() {
        let value = project(br"<root/>");
        let wrong_profile = MaterializationRequest::new(
            ProfileId::new("xml.1.0-unsafe", 1),
            MaterializationStyleId::new("xml.safe-canonical-document", 1),
        );
        assert!(matches!(
            materialize(&value, &wrong_profile),
            MaterializationResult::Failed(FailedMaterializationAttempt {
                failure: MaterializationFailure::UnsupportedProfile,
                ..
            })
        ));
        let wrong_style = MaterializationRequest::new(
            ProfileId::new("xml.1.0-safe", 1),
            MaterializationStyleId::new("xml.fancy", 1),
        );
        assert!(matches!(
            materialize(&value, &wrong_style),
            MaterializationResult::Failed(FailedMaterializationAttempt {
                failure: MaterializationFailure::UnsupportedStyle,
                ..
            })
        ));
    }

    #[test]
    fn provenance_is_target_bound_and_direct() {
        let value = project(br"<root a='1'>t</root>");
        let MaterializationResult::Complete(complete) = materialize(&value, &request()) else {
            panic!("must materialize");
        };
        assert!(
            complete.provenance.entries().len() >= 3,
            "root, attribute, and the text occurrence (with its fragment) must all map"
        );
        let outputs: usize = complete
            .provenance
            .entries()
            .iter()
            .map(|entry| entry.outputs.len())
            .sum();
        assert!(outputs >= 4, "fragment origins must not be lost");
        let target = complete.document.snapshot_identity();
        for entry in complete.provenance.entries() {
            for origin in &entry.outputs {
                assert_eq!(origin.snapshot, target);
                assert_eq!(origin.node.snapshot(), target);
                assert_eq!(origin.span.snapshot(), target);
            }
        }
    }

    #[test]
    fn projection_materialize_projection_is_stable() {
        // Strongest closure: project, materialize, reparse, project again;
        // the second record must equal the first exactly.
        let source = br#"<root xmlns:a="urn:a" a:kind="x"><a:item>v</a:item><!--c--></root>"#;
        let first = project(source);
        let MaterializationResult::Complete(complete) = materialize(&first, &request()) else {
            panic!("must materialize");
        };
        let reparsed = complete.document;
        let ProjectionResult::Complete(second) =
            reparsed.project(ProjectionRequest::element_tree())
        else {
            panic!("reparsed document must project");
        };
        assert_eq!(second.value, first, "projection is a fixed point");
    }

    fn element_value(local: &str, content: Vec<PortableValue>) -> PortableValue {
        let mut name = ObjectBuilder::new();
        name.insert("namespace", PortableValue::null())
            .expect("insert");
        name.insert("local", PortableValue::string(local))
            .expect("insert");
        let mut element = ObjectBuilder::new();
        element
            .insert("expanded-name", name.build())
            .expect("insert");
        if !content.is_empty() {
            element
                .insert("content", PortableValue::sequence(content))
                .expect("insert");
        }
        element.build()
    }

    fn text_item(text: &str) -> PortableValue {
        let mut fragment = ObjectBuilder::new();
        fragment
            .insert("kind", PortableValue::string("literal"))
            .expect("insert");
        fragment
            .insert("text", PortableValue::string(text))
            .expect("insert");
        let mut item = ObjectBuilder::new();
        item.insert("kind", PortableValue::string("text"))
            .expect("insert");
        item.insert("fragments", PortableValue::sequence(vec![fragment.build()]))
            .expect("insert");
        item.build()
    }

    fn cdata_item(text: &str) -> PortableValue {
        let mut item = ObjectBuilder::new();
        item.insert("kind", PortableValue::string("cdata"))
            .expect("insert");
        item.insert("text", PortableValue::string(text))
            .expect("insert");
        item.build()
    }

    fn comment_item(text: &str) -> PortableValue {
        let mut item = ObjectBuilder::new();
        item.insert("kind", PortableValue::string("comment"))
            .expect("insert");
        item.insert("text", PortableValue::string(text))
            .expect("insert");
        item.build()
    }

    fn pi_item(target: &str, content: Option<&str>) -> PortableValue {
        let mut item = ObjectBuilder::new();
        item.insert("kind", PortableValue::string("processing-instruction"))
            .expect("insert");
        item.insert("target", PortableValue::string(target))
            .expect("insert");
        if let Some(content) = content {
            item.insert("content", PortableValue::string(content))
                .expect("insert");
        }
        item.build()
    }

    fn record_with_root(root: PortableValue) -> PortableValue {
        let mut builder = ObjectBuilder::new();
        builder
            .insert("record", PortableValue::string("xml.element-tree@1"))
            .expect("insert");
        builder.insert("root", root).expect("insert");
        builder.build()
    }

    fn assert_failure(
        value: &PortableValue,
        request: &MaterializationRequest,
        expected: MaterializationFailure,
    ) {
        match materialize(value, request) {
            MaterializationResult::Failed(attempt) => {
                assert_eq!(
                    attempt.failure, expected,
                    "the exact failure variant must surface"
                );
            }
            MaterializationResult::Complete(complete) => panic!(
                "expected {expected:?} but materialization completed: {}",
                String::from_utf8_lossy(complete.document.render())
            ),
        }
    }

    #[test]
    fn failure_matrix_asserts_exact_variants() {
        // Unsupported request fields fail before the input is analyzed.
        assert_failure(
            &record_with_root(element_value("root", Vec::new())),
            &request().with_encoding(SourceEncoding::Latin1),
            MaterializationFailure::UnsupportedEncoding,
        );
        assert_failure(
            &record_with_root(element_value("root", Vec::new())),
            &request().with_newline(NewlinePolicy::None),
            MaterializationFailure::UnsupportedNewline,
        );

        // Unrepresentable content items fail during emission with the exact
        // variant and the offending input path. The path helper mirrors the
        // sequence-field path construction of the validator, which anchors
        // the `content` segment at the root of the value.
        let content_path = |index: u64| {
            ValuePath::root()
                .child(ValuePathSegment::ObjectValue("content".to_owned()))
                .child(ValuePathSegment::SequenceElement(index))
        };
        assert_failure(
            &record_with_root(element_value("root", vec![cdata_item("a]]>b")])),
            &request(),
            MaterializationFailure::Unrepresentable {
                path: content_path(0),
                kind: PortableValueKind::String,
            },
        );
        assert_failure(
            &record_with_root(element_value("root", vec![comment_item("a--b")])),
            &request(),
            MaterializationFailure::Unrepresentable {
                path: content_path(0),
                kind: PortableValueKind::String,
            },
        );
        assert_failure(
            &record_with_root(element_value("root", vec![pi_item("xml", None)])),
            &request(),
            MaterializationFailure::Unrepresentable {
                path: content_path(0),
                kind: PortableValueKind::String,
            },
        );
        assert_failure(
            &record_with_root(element_value("root", vec![pi_item("pi", Some("x?>y"))])),
            &request(),
            MaterializationFailure::Unrepresentable {
                path: content_path(0),
                kind: PortableValueKind::String,
            },
        );

        // An entity replacement carrying markup cannot be represented.
        let mut entity = ObjectBuilder::new();
        entity
            .insert("name", PortableValue::string("e"))
            .expect("insert");
        entity
            .insert("replacement", PortableValue::string("a<b"))
            .expect("insert");
        let mut record = ObjectBuilder::new();
        record
            .insert("record", PortableValue::string("xml.element-tree@1"))
            .expect("insert");
        record
            .insert("entities", PortableValue::sequence(vec![entity.build()]))
            .expect("insert");
        record
            .insert("root", element_value("root", Vec::new()))
            .expect("insert");
        assert_failure(
            &record.build(),
            &request(),
            MaterializationFailure::Unrepresentable {
                path: ValuePath::root()
                    .child(ValuePathSegment::ObjectValue("entities".to_owned()))
                    .child(ValuePathSegment::SequenceElement(0))
                    .child(ValuePathSegment::ObjectValue("replacement".to_owned())),
                kind: PortableValueKind::String,
            },
        );

        // A declaration promising a non-1.0 version cannot be represented.
        let mut declaration = ObjectBuilder::new();
        declaration
            .insert("version", PortableValue::string("1.1"))
            .expect("insert");
        let mut record = ObjectBuilder::new();
        record
            .insert("record", PortableValue::string("xml.element-tree@1"))
            .expect("insert");
        record
            .insert("declaration", declaration.build())
            .expect("insert");
        record
            .insert("root", element_value("root", Vec::new()))
            .expect("insert");
        assert_failure(
            &record.build(),
            &request(),
            MaterializationFailure::Unrepresentable {
                path: ValuePath::root()
                    .child(ValuePathSegment::ObjectValue("declaration".to_owned()))
                    .child(ValuePathSegment::ObjectValue("version".to_owned())),
                kind: PortableValueKind::String,
            },
        );

        // Tightened resource limits fail with the exact limit name.
        let big = record_with_root(element_value(
            "root",
            vec![element_value("child", vec![text_item("longer text")])],
        ));
        assert_failure(
            &big,
            &request().with_limits(MaterializationLimits {
                max_output_bytes: 16,
                ..MaterializationLimits::default()
            }),
            MaterializationFailure::ResourceLimit("output-bytes"),
        );
        assert_failure(
            &record_with_root(element_value("root", Vec::new())),
            &request().with_limits(MaterializationLimits {
                max_input_nodes: 1,
                ..MaterializationLimits::default()
            }),
            MaterializationFailure::ResourceLimit("input-nodes"),
        );
    }
}
