[package]
name = "consema-json"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Lossless JSON and JSONC implementation for Consema"

[dependencies]
consema-core = { path = "../consema-core", version = "0.2.0" }
consema-document = { path = "../consema-document", version = "0.2.0" }

[lints]
workspace = true
