[package]
name = "consema-json"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Lossless JSON, JSONC, and JSON5 implementation for Consema"

[dependencies]
consema-core = { path = "../consema-core", version = "0.13.0" }
consema-document = { path = "../consema-document", version = "0.13.0" }
unicode-id-start.workspace = true

[lints]
workspace = true
